apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-browser
  labels:
    app: nginx-browser
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx-browser
  template:
    metadata:
      labels:
        app: nginx-browser
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: nginx-browser
        image: nginx:latest
        imagePullPolicy: "Always"
        
